gateway: FORCE_COLOR=1 uv run uvicorn gateway.main:app --host 0.0.0.0 --port 8000 --reload
auth: FORCE_COLOR=1 uv run uvicorn services.auth.main:app --host 0.0.0.0 --port 8001 --reload
game: FORCE_COLOR=1 uv run uvicorn services.game_logic.main:app --host 0.0.0.0 --port 8004 --reload
ai: FORCE_COLOR=1 uv run uvicorn services.ai_word_generator.main:app --host 0.0.0.0 --port 8003 --reload
